# Generated by Django 3.2.25 on 2026-06-18 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0206_auto_20260607_0834'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='hide_problem_source',
            field=models.BooleanField(default=False, help_text='Whether problem source should be hidden by default.', verbose_name='hide problem source'),
        ),
    ]
